config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get "/users/sign_in" => redirect("/")

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :documents

  unauthenticated do
    root :to => 'sessions#index'
  end

  authenticated do
    root :to => 'dashboard#index'
  end

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/configuration', to: 'dashboard#configuration'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
	belongs_to :user
	validates :title, :content, presence: true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  validates_presence_of :accept
end

app/models/user.rb
class User < ApplicationRecord
  has_one :permission

  devise :database_authenticatable, :timeoutable, :omniauthable, :omniauth_providers => [:google_oauth2]
  
  def self.from_omniauth(auth)
    # where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    where(email: auth.info.email).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
      user.email = auth.info.email
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!, :expired_token?
  layout 'user_session'

  private

  def expired_token?
    sign_out current_user unless current_user.persisted?
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController

  def index
    begin
      @permission = Permission.find_by_user_id(current_user) || Permission.new
      Drive::Folder.new(current_user) unless  @permission.accept
      @documents = build_drive.list
    rescue
      sign_out current_user
      redirect_to root_path
    end
  end

  private

  def build_drive
    @drive = Drive::DocumentFile.new(current_user)
  end

end

app/controllers/documents_controller.rb
class DocumentsController < BaseController
  respond_to :html, :json
  before_action :build_drive, only: [:create, :update, :destroy]
  before_action :find_document, only: [:edit,  :update, :destroy]
  
  def new
    @document = Document.new
    @document.content = Faker::Lorem.paragraph
    respond_with(@document)
  end

  def create
    begin
      @document = Document.new(document_params)
      @document.user = current_user
      if @document.valid?
        @drive.create(@document)
      else
        render
      end
    rescue Exception => e
      
    end
  end

  def edit
    
  end

  def update
    @document.update_attributes(document_params)
    if @document.valid?
      @drive.update(@document)
    else
      render
    end
  end

  def destroy
    @drive.destroy(@document)
  end

  private

  def document_params
    params.require(:document).permit(:title, :content)
  end

  def build_drive
    @drive = Drive::DocumentFile.new(current_user)
  end

  def find_document
    @document = Document.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
    end
    redirect_to '/dashboard'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/drive_helper.rb
module DriveHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboard/index.html.slim
.content
  .row
    .col-md-12
      .text-right
        = link_to 'Novo documento', new_document_path, class: 'btn btn-primary btn-sm'

  .row.mt-4
    .col-md-12
      table.table.table-hover.table-sm
        thead
          tr
            th 
              small #
            th(scope="col") 
              small Nome
            th(scope="col") 
              small Criado em
            th
            th
        tbody
          - @documents.each do |document|
            tr
              td 
                small = document.id
              td 
                small = document.title
              td 
                small = I18n.l(document.created_at, format: :long)
              td
                small
                  = link_to 'Editar', edit_document_path(document)
              th
                small
                  = link_to 'Excluir', document_path(document), method: :delete, :remote => true, data: { confirm: "Você tem certeza em remover o documento '#{document.title}'?" }

javascript:

app/views/documents/_form.html.slim
.row
  .col-md-12
    = form_for(@document, remote: true) do |f|
      .card
        .card-header 
          = f.text_field :title, class: 'title form-control', placeholder: "Título do documento"
        .card-body
          .row
            .col-md-12
              = f.text_area :content, id: 'editor'
        .card-footer.text-right
          = f.submit 'Salvar documento', class: 'btn-primary btn btn-sm', id: 'save_doc', data: { disable_with: "Salvando ..." }

javascript:
  $(document).ready( function() {
    $('#editor').summernote({
      tabsize: 2,
      height: 300,
      focus: true
    });
  });

app/views/documents/create.js.erb
<% if (@document.errors.any?) %>
	swal("Atenção", "<%= @document.errors.full_messages.first %>" , "warning")
<% else %>
	swal({ title: "Sucesso", text: "O documento está salvo no Google Drive", type: "success", timer: 2000, showConfirmButton: false },
			function() { window.location.href = "<%= dashboard_path  %>"; })
<% end %>

app/views/documents/destroy.js.erb
swal({ title: "Sucesso", text: "O documento foi removido no Google Drive", type: "success", timer: 2000, showConfirmButton: false }, 
	function() { window.location.href = "<%= dashboard_path  %>"; })

app/views/documents/edit.html.slim
= render partial: 'form'

app/views/documents/new.html.slim
= render partial: 'form'

app/views/documents/update.js.erb
<% if (@document.errors.any?) %>
	swal("Atenção", "<%= @document.errors.full_messages.first %>" , "warning")
<% else %>
	swal({ title: "Sucesso", text: "O documento está salvo no Google Drive", type: "success", timer: 2000, showConfirmButton: false },
			function() { window.location.href = "<%= dashboard_path  %>"; })
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App IDox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container'>
    <%= yield %>
  </body>
</html>

app/views/layouts/user_session.html.slim
doctype html
html
  head
    title App IDox Dashboard
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  body
    nav.navbar.navbar-light.bg-dark
      span.navbar-brand.mb-0.h1.text-white App IDox
      small.text-white
        = "#{current_user.name} (#{current_user.email})"
      small.text-right.text-white
        = link_to('Logout', destroy_user_session_path, method: :delete, class: 'text-white')
    .container.mt-4
      = yield